/**
 * Spec for the WeatherDirective.
 *
 * DO NOT EDIT THIS FILE.
 */
describe('WeatherDirective', function() {
  var $httpBackend, element, scope;

  beforeEach(module('cfAngularExercise'));

  beforeEach(inject(function($injector) {
    var $rootScope = $injector.get('$rootScope');
    var $compile = $injector.get('$compile');
    $httpBackend = $injector.get('$httpBackend');
    var expectedCity = {
      name: "Toronto",
      high: 15,
      low: 9,
      forecast: 'Sunny'
    };
    $httpBackend.expectGET('/weather/toronto.json').respond(200, expectedCity);
    scope = $rootScope.$new();

    element = '<city-weather city="toronto"></city-weather>';

    element = $compile(element)(scope);
    $httpBackend.flush();
  }));

  it('populates HTML template correctly', function() {
    expect(element.find('strong').text()).toBe('Toronto');
    expect(element.find('span').text()).toBe('Sunny');
    expect(element.find('emphasis').text()).toBe('15 °C');
  });

});
